In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import EditedNearestNeighbours
from imblearn.under_sampling import NearMiss
from imblearn.under_sampling import TomekLinks
from imblearn.under_sampling import OneSidedSelection
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [3]:
credit_card_data=pd.read_csv("creditcard.csv.zip")

In [4]:
x=credit_card_data.drop(columns='Class',axis=1)
y=credit_card_data['Class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

print(x.shape,x_train.shape,x_test.shape)

(284807, 30) (227845, 30) (56962, 30)


In [4]:
nearmiss = NearMiss(version=1) 
x_train_nearmiss, y_train_nearmiss = nearmiss.fit_resample(x_train, y_train)
print("Before NearMiss:", y_train.value_counts())
print("After NearMiss:", pd.Series(y_train_nearmiss).value_counts())

Before NearMiss: 0    227437
1       408
Name: Class, dtype: int64
After NearMiss: 0    408
1    408
Name: Class, dtype: int64


In [7]:
tomek_links = TomekLinks()
x_train_tomek, y_train_tomek = tomek_links.fit_resample(x_train, y_train)
print("Before Tomek Links Sampling:", y_train.value_counts())
print("After Tomek Links Sampling:", pd.Series(y_train_tomek).value_counts())

Before Tomek Links Sampling: 0    227437
1       408
Name: Class, dtype: int64
After Tomek Links Sampling: 0    227364
1       408
Name: Class, dtype: int64


In [11]:
enn = EditedNearestNeighbours(n_neighbors=3) 
x_train_enn, y_train_enn = enn.fit_resample(x_train, y_train)
print("Before ENN Sampling:", y_train.value_counts())
print("After ENN Sampling:", pd.Series(y_train_enn).value_counts())

Before ENN Sampling: 0    227437
1       408
Name: Class, dtype: int64
After ENN Sampling: 0    227048
1       408
Name: Class, dtype: int64


In [14]:
oss = OneSidedSelection(random_state=42, n_neighbors=3)  
x_train_oss, y_train_oss = oss.fit_resample(x_train, y_train)
print("Before OSS Sampling:", y_train.value_counts())
print("After OSS Sampling:", pd.Series(y_train_oss).value_counts())

Before OSS Sampling: 0    227437
1       408
Name: Class, dtype: int64
After OSS Sampling: 0    227364
1       408
Name: Class, dtype: int64


In [17]:
from imblearn.under_sampling import NeighbourhoodCleaningRule
ncr = NeighbourhoodCleaningRule(n_neighbors=3, kind_sel="all")  
x_train_ncr, y_train_ncr = ncr.fit_resample(x_train, y_train)
print("Before NCR Sampling:", y_train.value_counts())
print("After NCR Sampling:", pd.Series(y_train_ncr).value_counts())

Before NCR Sampling: 0    227437
1       408
Name: Class, dtype: int64
After NCR Sampling: 0    226372
1       408
Name: Class, dtype: int64


In [40]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
x_train_resampled, y_train_resampled = rus.fit_resample(x_train, y_train)
print("Before Undersampling:", y_train.value_counts())
print("After Undersampling:", pd.Series(y_train_resampled).value_counts())

Before Undersampling: 0    227437
1       408
Name: Class, dtype: int64
After Undersampling: 0    408
1    408
Name: Class, dtype: int64


In [19]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_nearmiss, y_train_nearmiss)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[45633 11245]
 [    8    76]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.80      0.89     56878
           1       0.01      0.90      0.01        84

    accuracy                           0.80     56962
   macro avg       0.50      0.85      0.45     56962
weighted avg       1.00      0.80      0.89     56962

Accuracy Score: 0.8024472455321091


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_tomek, y_train_tomek)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56835    43]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.60      0.76      0.67        84

    accuracy                           1.00     56962
   macro avg       0.80      0.88      0.83     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9988939995084443


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_enn, y_train_enn)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Confusion Matrix:
 [[56854    24]
 [   25    59]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.71      0.70      0.71        84

    accuracy                           1.00     56962
   macro avg       0.86      0.85      0.85     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9991397773954567


In [22]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_oss, y_train_oss)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56841    37]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.63      0.76      0.69        84

    accuracy                           1.00     56962
   macro avg       0.82      0.88      0.85     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9989993328885924


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [23]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_ncr, y_train_ncr)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56836    42]
 [   18    66]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.61      0.79      0.69        84

    accuracy                           1.00     56962
   macro avg       0.81      0.89      0.84     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9989466661985184


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_resampled, y_train_resampled)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[53464  3414]
 [    9    75]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.94      0.97     56878
           1       0.02      0.89      0.04        84

    accuracy                           0.94     56962
   macro avg       0.51      0.92      0.51     56962
weighted avg       1.00      0.94      0.97     56962

Accuracy Score: 0.9399073066254696


In [24]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_nearmiss, y_train_nearmiss)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[34107 22771]
 [    4    80]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.60      0.75     56878
           1       0.00      0.95      0.01        84

    accuracy                           0.60     56962
   macro avg       0.50      0.78      0.38     56962
weighted avg       1.00      0.60      0.75     56962

Accuracy Score: 0.6001720445209087


In [25]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_tomek, y_train_tomek)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56855    23]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.74      0.76      0.75        84

    accuracy                           1.00     56962
   macro avg       0.87      0.88      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9992451107756047


In [26]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_enn, y_train_enn)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56854    24]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.73      0.76      0.74        84

    accuracy                           1.00     56962
   macro avg       0.86      0.88      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9992275552122467


In [27]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_oss, y_train_oss)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56855    23]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.74      0.76      0.75        84

    accuracy                           1.00     56962
   macro avg       0.87      0.88      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9992451107756047


In [28]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_ncr, y_train_ncr)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56853    25]
 [   20    64]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.72      0.76      0.74        84

    accuracy                           1.00     56962
   macro avg       0.86      0.88      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9992099996488887


In [42]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_resampled, y_train_resampled)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[51258  5620]
 [    7    77]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.90      0.95     56878
           1       0.01      0.92      0.03        84

    accuracy                           0.90     56962
   macro avg       0.51      0.91      0.49     56962
weighted avg       1.00      0.90      0.95     56962

Accuracy Score: 0.9012148449843755


In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_nearmiss, y_train_nearmiss)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[ 4662 52216]
 [    6    78]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.08      0.15     56878
           1       0.00      0.93      0.00        84

    accuracy                           0.08     56962
   macro avg       0.50      0.51      0.08     56962
weighted avg       1.00      0.08      0.15     56962

Accuracy Score: 0.08321337031705348


In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_tomek, y_train_tomek)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56878     0]
 [   77     7]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       1.00      0.08      0.15        84

    accuracy                           1.00     56962
   macro avg       1.00      0.54      0.58     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9986482216214319


In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_enn, y_train_enn)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56877     1]
 [   76     8]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.89      0.10      0.17        84

    accuracy                           1.00     56962
   macro avg       0.94      0.55      0.59     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9986482216214319


In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_oss, y_train_oss)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56878     0]
 [   77     7]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       1.00      0.08      0.15        84

    accuracy                           1.00     56962
   macro avg       1.00      0.54      0.58     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9986482216214319


In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_ncr, y_train_ncr)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56877     1]
 [   76     8]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.89      0.10      0.17        84

    accuracy                           1.00     56962
   macro avg       0.94      0.55      0.59     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9986482216214319


In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_resampled, y_train_resampled)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[35988 20890]
 [   25    59]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.63      0.77     56878
           1       0.00      0.70      0.01        84

    accuracy                           0.63     56962
   macro avg       0.50      0.67      0.39     56962
weighted avg       1.00      0.63      0.77     56962

Accuracy Score: 0.6328253923668411


In [34]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_nearmiss, y_train_nearmiss)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[48014  8864]
 [    9    75]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.84      0.92     56878
           1       0.01      0.89      0.02        84

    accuracy                           0.84     56962
   macro avg       0.50      0.87      0.47     56962
weighted avg       1.00      0.84      0.91     56962

Accuracy Score: 0.8442294863242161


In [35]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_tomek, y_train_tomek)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   18    66]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.79      0.85        84

    accuracy                           1.00     56962
   macro avg       0.96      0.89      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9995962220427653


In [36]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_enn, y_train_enn)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   17    67]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.80      0.86        84

    accuracy                           1.00     56962
   macro avg       0.97      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996137776061234


In [37]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_oss, y_train_oss)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   15    69]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.82      0.87        84

    accuracy                           1.00     56962
   macro avg       0.97      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996488887328394


In [38]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_ncr, y_train_ncr)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   16    68]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.81      0.87        84

    accuracy                           1.00     56962
   macro avg       0.97      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996313331694814


In [44]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_resampled, y_train_resampled)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[55344  1534]
 [    9    75]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.97      0.99     56878
           1       0.05      0.89      0.09        84

    accuracy                           0.97     56962
   macro avg       0.52      0.93      0.54     56962
weighted avg       1.00      0.97      0.98     56962

Accuracy Score: 0.9729117657385625
