In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.over_sampling import SVMSMOTE
from imblearn.over_sampling import ADASYN
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [3]:
credit_card_data=pd.read_csv("creditcard.csv.zip")

In [4]:
x=credit_card_data.drop(columns='Class',axis=1)
y=credit_card_data['Class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

print(x.shape,x_train.shape,x_test.shape)


(284807, 30) (227845, 30) (56962, 30)


In [15]:
borderline_smote = BorderlineSMOTE(random_state=42, kind='borderline-1')  
x_train_Bsmote, y_train_Bsmote = borderline_smote.fit_resample(x_train, y_train)
print("Before Borderline-SMOTE:", y_train.value_counts())
print("After Borderline-SMOTE:", pd.Series(y_train_Bsmote).value_counts())

Before Borderline-SMOTE: 0    227437
1       408
Name: Class, dtype: int64
After Borderline-SMOTE: 0    227437
1    227437
Name: Class, dtype: int64


In [5]:
random_oversampler = RandomOverSampler(random_state=42)
x_train_oversampled, y_train_oversampled = random_oversampler.fit_resample(x_train, y_train)
print("Before Oversampling:", y_train.value_counts())
print("After Oversampling:", pd.Series(y_train_oversampled).value_counts())

Before Oversampling: 0    227437
1       408
Name: Class, dtype: int64
After Oversampling: 0    227437
1    227437
Name: Class, dtype: int64


In [5]:
svm_smote = SVMSMOTE(random_state=42)
x_train_SVsmote, y_train_SVsmote = svm_smote.fit_resample(x_train, y_train)
print("Before SVM-SMOTE:", y_train.value_counts())
print("After SVM-SMOTE:", pd.Series(y_train_SVsmote).value_counts())

Before SVM-SMOTE: 0    227437
1       408
Name: Class, dtype: int64
After SVM-SMOTE: 0    227437
1    227437
Name: Class, dtype: int64


In [8]:
adasyn = ADASYN(random_state=42)
x_train_adasyn, y_train_adasyn = adasyn.fit_resample(x_train, y_train)
print("Before ADASYN:", y_train.value_counts())
print("After ADASYN:", pd.Series(y_train_adasyn).value_counts())

Before ADASYN: 0    227437
1       408
Name: Class, dtype: int64
After ADASYN: 0    227437
1    227312
Name: Class, dtype: int64


In [21]:
smote = SMOTE(random_state=42)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)
print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", pd.Series(y_train_smote).value_counts())
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_smote, y_train_smote)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Before SMOTE: 0    227437
1       408
Name: Class, dtype: int64
After SMOTE: 0    227437
1    227437
Name: Class, dtype: int64
Confusion Matrix:
 [[55931   947]
 [    8    76]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     56878
           1       0.07      0.90      0.14        84

    accuracy                           0.98     56962
   macro avg       0.54      0.94      0.56     56962
weighted avg       1.00      0.98      0.99     56962

Accuracy Score: 0.9832344369930831


In [28]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_oversampled, y_train_oversampled)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[54844  2034]
 [    9    75]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98     56878
           1       0.04      0.89      0.07        84

    accuracy                           0.96     56962
   macro avg       0.52      0.93      0.53     56962
weighted avg       1.00      0.96      0.98     56962

Accuracy Score: 0.9641339840595484


In [6]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_SVsmote, y_train_SVsmote)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56456   422]
 [   10    74]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00     56878
           1       0.15      0.88      0.26        84

    accuracy                           0.99     56962
   macro avg       0.57      0.94      0.63     56962
weighted avg       1.00      0.99      1.00     56962

Accuracy Score: 0.9924159966293319


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_adasyn, y_train_adasyn)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[55900   978]
 [    8    76]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     56878
           1       0.07      0.90      0.13        84

    accuracy                           0.98     56962
   macro avg       0.54      0.94      0.56     56962
weighted avg       1.00      0.98      0.99     56962

Accuracy Score: 0.9826902145289842


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_Bsmote, y_train_Bsmote)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56105   773]
 [    9    75]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     56878
           1       0.09      0.89      0.16        84

    accuracy                           0.99     56962
   macro avg       0.54      0.94      0.58     56962
weighted avg       1.00      0.99      0.99     56962

Accuracy Score: 0.986271549454022


In [18]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_SVsmote, y_train_SVsmote)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56847    31]
 [   17    67]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.68      0.80      0.74        84

    accuracy                           1.00     56962
   macro avg       0.84      0.90      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9991573329588147


In [29]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_oversampled, y_train_oversampled)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56850    28]
 [   23    61]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.69      0.73      0.71        84

    accuracy                           1.00     56962
   macro avg       0.84      0.86      0.85     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9991046662687406


In [19]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_adasyn, y_train_adasyn)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56784    94]
 [   14    70]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.43      0.83      0.56        84

    accuracy                           1.00     56962
   macro avg       0.71      0.92      0.78     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9981039991573329


In [22]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_smote, y_train_smote)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56761   117]
 [   19    65]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.36      0.77      0.49        84

    accuracy                           1.00     56962
   macro avg       0.68      0.89      0.74     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9976124433833081


In [17]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_Bsmote, y_train_Bsmote)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56848    30]
 [   16    68]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.69      0.81      0.75        84

    accuracy                           1.00     56962
   macro avg       0.85      0.90      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9991924440855307


In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_Bsmote, y_train_Bsmote)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56649   229]
 [   60    24]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.09      0.29      0.14        84

    accuracy                           0.99     56962
   macro avg       0.55      0.64      0.57     56962
weighted avg       1.00      0.99      1.00     56962

Accuracy Score: 0.9949264421895299


In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_oversampled, y_train_oversampled)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56794    84]
 [   59    25]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.23      0.30      0.26        84

    accuracy                           1.00     56962
   macro avg       0.61      0.65      0.63     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.997489554439802


In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_SVsmote, y_train_SVsmote)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56662   216]
 [   60    24]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.10      0.29      0.15        84

    accuracy                           1.00     56962
   macro avg       0.55      0.64      0.57     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9951546645131842


In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_adasyn, y_train_adasyn)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[53764  3114]
 [   30    54]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.97     56878
           1       0.02      0.64      0.03        84

    accuracy                           0.94     56962
   macro avg       0.51      0.79      0.50     56962
weighted avg       1.00      0.94      0.97     56962

Accuracy Score: 0.9448053088023595


In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_smote, y_train_smote)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[53846  3032]
 [   30    54]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.97     56878
           1       0.02      0.64      0.03        84

    accuracy                           0.95     56962
   macro avg       0.51      0.79      0.50     56962
weighted avg       1.00      0.95      0.97     56962

Accuracy Score: 0.9462448649977178


In [34]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_smote, y_train_smote)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56867    11]
 [   12    72]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.87      0.86      0.86        84

    accuracy                           1.00     56962
   macro avg       0.93      0.93      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9995962220427653


In [31]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_Bsmote, y_train_Bsmote)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   14    70]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.83      0.88        84

    accuracy                           1.00     56962
   macro avg       0.97      0.92      0.94     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996664442961974


In [32]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_SVsmote, y_train_SVsmote)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   13    71]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.85      0.89        84

    accuracy                           1.00     56962
   macro avg       0.97      0.92      0.94     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996839998595555


In [34]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_adasyn, y_train_adasyn)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56869     9]
 [   12    72]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.89      0.86      0.87        84

    accuracy                           1.00     56962
   macro avg       0.94      0.93      0.94     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996313331694814


In [6]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_oversampled, y_train_oversampled)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56873     5]
 [   15    69]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.93      0.82      0.87        84

    accuracy                           1.00     56962
   macro avg       0.97      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996488887328394
