In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [4]:
credit_card_data=pd.read_csv("creditcard.csv.zip")

In [5]:
X = credit_card_data.drop('Class', axis=1)
y = credit_card_data['Class']

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

NameError: name 'StandardScaler' is not defined

In [7]:
log_model = LogisticRegression(max_iter=1000)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
knn_model = KNeighborsClassifier(n_neighbors=5)

In [8]:
ensemble_model = VotingClassifier(
    estimators=[('logistic', log_model), ('random_forest', rf_model), ('knn', knn_model)],
    voting='hard' 
)

In [9]:
ensemble_model.fit(X_train, y_train)

VotingClassifier(estimators=[('logistic', LogisticRegression(max_iter=1000)),
                             ('random_forest',
                              RandomForestClassifier(random_state=42)),
                             ('knn', KNeighborsClassifier())])

In [10]:
y_pred = ensemble_model.predict(X_test)

In [11]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9992
Precision: 0.9722
Recall: 0.5147
F1 Score: 0.6731
Confusion Matrix:
 [[85305     2]
 [   66    70]]


In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

In [14]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [15]:
y_pred = rf_model.predict(X_test)

In [16]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9996
Precision: 0.9478
Recall: 0.8015
F1 Score: 0.8685
Confusion Matrix:
 [[85301     6]
 [   27   109]]


In [17]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
subspace_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_features=0.5,  
    random_state=42
)

In [18]:
subspace_model.fit(X_train, y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_features=0.5,
                  n_estimators=100, random_state=42)

In [19]:
y_pred = subspace_model.predict(X_test)

In [20]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9996
Precision: 0.9643
Recall: 0.7941
F1 Score: 0.8710
Confusion Matrix:
 [[85303     4]
 [   28   108]]


In [21]:
from sklearn.ensemble import GradientBoostingClassifier

In [22]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

In [23]:
gb_model.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [24]:
y_pred = gb_model.predict(X_test)

In [25]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9986
Precision: 0.8947
Recall: 0.1250
F1 Score: 0.2194
Confusion Matrix:
 [[85305     2]
 [  119    17]]


In [26]:
from xgboost import XGBClassifier

In [27]:
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

In [28]:
xgb_model.fit(X_train, y_train)

C:\Users\fazila yousuf\AppData\Roaming\Python\Python310\site-packages\xgboost\core.py:158: UserWarning: [14:50:23] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [29]:
y_pred = xgb_model.predict(X_test)

In [30]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9996
Precision: 0.9174
Recall: 0.8162
F1 Score: 0.8638
Confusion Matrix:
 [[85297    10]
 [   25   111]]


In [31]:
from sklearn.ensemble import AdaBoostClassifier

In [32]:
adaboost_model = AdaBoostClassifier(
    base_estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [33]:
adaboost_model.fit(X_train, y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.1, n_estimators=100, random_state=42)

In [34]:
y_pred = adaboost_model.predict(X_test)

In [35]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9994
Precision: 0.8868
Recall: 0.6912
F1 Score: 0.7769
Confusion Matrix:
 [[85295    12]
 [   42    94]]


In [36]:
from catboost import CatBoostClassifier

In [37]:
from catboost import CatBoostClassifier

In [38]:
catboost_model = CatBoostClassifier(
    iterations=100,
    learning_rate=0.1,
    depth=6,
    random_state=42,
    verbose=0
)

In [39]:
catboost_model.fit(X_train, y_train)

In [40]:
y_pred = catboost_model.predict(X_test)


In [41]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")

Accuracy: 0.9997
Precision: 0.9573
Recall: 0.8235
F1 Score: 0.8854
Confusion Matrix:
 [[85302     5]
 [   24   112]]


In [42]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [43]:
estimators = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('dt', DecisionTreeClassifier(max_depth=5, random_state=42))
]

In [44]:
meta_classifier = LogisticRegression(max_iter=1000, random_state=42)


stacking_model = StackingClassifier(
    estimators=estimators,
    final_estimator=meta_classifier
)

In [ ]:
stacking_model.fit(X_train, y_train)

In [ ]:
y_pred = stacking_model.predict(X_test)

In [ ]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")