In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [2]:
credit_card_data=pd.read_csv("creditcard.csv.zip")

In [3]:
x=credit_card_data.drop(columns='Class',axis=1)
y=credit_card_data['Class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

print(x.shape,x_train.shape,x_test.shape)

(284807, 30) (227845, 30) (56962, 30)


In [11]:
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE
smote_enn = SMOTEENN(smote=SMOTE(random_state=42), random_state=42)
x_train_SMOTEENN, y_train_SMOTEENN = smote_enn.fit_resample(x_train, y_train)
print("Before SMOTEENN Sampling:", y_train.value_counts())
print("After SMOTEENN Sampling:", pd.Series(y_train_SMOTEENN).value_counts())

Before SMOTEENN Sampling: 0    227437
1       408
Name: Class, dtype: int64
After SMOTEENN Sampling: 1    219210
0    210120
Name: Class, dtype: int64


In [12]:
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smote_tomek = SMOTETomek(smote=SMOTE(random_state=42), random_state=42)
x_train_SMOTETomek, y_train_SMOTETomek = smote_tomek.fit_resample(x_train, y_train)
print("Before SMOTETomek Sampling:", y_train.value_counts())
print("After SMOTETomek Sampling:", pd.Series(y_train_SMOTETomek).value_counts())

Before SMOTETomek Sampling: 0    227437
1       408
Name: Class, dtype: int64
After SMOTETomek Sampling: 0    226875
1    226875
Name: Class, dtype: int64


In [13]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_SMOTETomek, y_train_SMOTETomek)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[55096  1782]
 [   10    74]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.97      0.98     56878
           1       0.04      0.88      0.08        84

    accuracy                           0.97     56962
   macro avg       0.52      0.92      0.53     56962
weighted avg       1.00      0.97      0.98     56962

Accuracy Score: 0.9685404304624136


In [14]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_SMOTETomek, y_train_SMOTETomek)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56759   119]
 [   17    67]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.36      0.80      0.50        84

    accuracy                           1.00     56962
   macro avg       0.68      0.90      0.75     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9976124433833081


In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_SMOTETomek, y_train_SMOTETomek)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[53850  3028]
 [   30    54]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.97     56878
           1       0.02      0.64      0.03        84

    accuracy                           0.95     56962
   macro avg       0.51      0.79      0.50     56962
weighted avg       1.00      0.95      0.97     56962

Accuracy Score: 0.9463150872511499


In [16]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_SMOTETomek, y_train_SMOTETomek)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56868    10]
 [   12    72]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.88      0.86      0.87        84

    accuracy                           1.00     56962
   macro avg       0.94      0.93      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9996137776061234


In [17]:
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(x_train_SMOTEENN, y_train_SMOTEENN)
y_pred = logistic_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[55500  1378]
 [    8    76]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     56878
           1       0.05      0.90      0.10        84

    accuracy                           0.98     56962
   macro avg       0.53      0.94      0.54     56962
weighted avg       1.00      0.98      0.99     56962

Accuracy Score: 0.975667989185773


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train_SMOTEENN, y_train_SMOTEENN)
y_pred = decision_tree.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56778   100]
 [   17    67]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.40      0.80      0.53        84

    accuracy                           1.00     56962
   macro avg       0.70      0.90      0.77     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9979459990871107


In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(x_train_SMOTEENN, y_train_SMOTEENN)
y_pred = knn.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[52680  4198]
 [   30    54]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.93      0.96     56878
           1       0.01      0.64      0.02        84

    accuracy                           0.93     56962
   macro avg       0.51      0.78      0.49     56962
weighted avg       1.00      0.93      0.96     56962

Accuracy Score: 0.9257750781222569


In [20]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42, n_estimators=100)
random_forest.fit(x_train_SMOTEENN, y_train_SMOTEENN)
y_pred = random_forest.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[56865    13]
 [   11    73]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56878
           1       0.85      0.87      0.86        84

    accuracy                           1.00     56962
   macro avg       0.92      0.93      0.93     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy Score: 0.9995786664794073
